[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name =  "magma-rsam"
version = "2.0.0"
authors = [
    {name = "Martanto", email = "martanto@live.com"},
]
description = "Calculating RSAM Value"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["seismic", "volcano", "volcanology", "convert", "sds", "seiscomp", "mseed"]
requires-python = ">=3.11"
dependencies = [

]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
base = [
    "obspy",
    "openpyxl",
    "pandas",
    "numpy",
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/martanto/magma-rsam"
Issues = "https://github.com/martanto/magma-rsam/issues"